[workspace]
authors = ["Jakob Everding <jakob.everding@uni-hamburg.de>"]
channels = ["conda-forge"]
name = "000_template"
platforms = ["win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
