name: Update commit hash and compile LaTeX
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  update_commit_hash_and_compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Update commit_hash.tex with current commit hash
        run: |
          echo -e "${GITHUB_SHA}\n" > writing/output/references/commit_hash.tex
      - name: Commit and push changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5
        with:
          message: 'Update commit hash, LaTeX to pdf'
